services:
  db:
    image: mysql:8.0
    container_name: mood_db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: America/Monterrey
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Ejecuta el script SQL al crear el contenedor por primera vez
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: mood_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    environment:
      - DB_HOST=db # Apunta al nombre del servicio contenedor de arriba
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - PORT=3000
      - TZ=America/Monterrey
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: